---
ID: "194aed96-26a9-486d-94f1-543397931691"
Parent: "6da35172-3775-4f53-b92e-dfaf1405f979"
Template: "6da35172-3775-4f53-b92e-dfaf1405f979"
Path: /sitecore/templates/Project/SitecoreHackathon/Content Types/Faq/Faq/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T034559Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
