---
ID: "ddbf6efe-3460-4a93-bd14-0c1a7baa4139"
Parent: "b1b66da1-ec87-4f51-9759-9e4964b2ae0a"
Template: "b1b66da1-ec87-4f51-9759-9e4964b2ae0a"
Path: /sitecore/templates/Feature/Teams/_Basic Team/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T164309Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
