
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All


namespace Hackathon.Feature.Teams
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Hackathon.Foundation.DataAccess.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{b1b66da1-ec87-4f51-9759-9e4964b2ae0a}", "", "Feature.Teams")]
    [SitecoreType(TemplateId = Hackathon.Feature.Teams.Constants.BasicTeam.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IBasicTeam : global::Hackathon.Feature.Teams.IHasTeamName, global::Hackathon.Feature.Teams.IHasMembers
    {
        
    }

}

namespace Hackathon.Feature.Teams.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct BasicTeam
    {
        public const string TemplateIdString = "b1b66da1-ec87-4f51-9759-9e4964b2ae0a";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
    }
}

namespace Hackathon.Feature.Teams
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Hackathon.Foundation.DataAccess.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{1b7e5c2f-5240-4ac4-aaff-c6ef5d29623f}", "", "Feature.Teams")]
    [SitecoreType(TemplateId = Hackathon.Feature.Teams.Constants.HasMembers.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IHasMembers : IGlassBase
    {
        
        /// <summary>Represents the Members field (fd1b8fc6-ce8f-4742-8973-50d07e582942).</summary>
        [SitecoreField(FieldName = Hackathon.Feature.Teams.Constants.HasMembers.Fields.Members_FieldName)]
        IEnumerable<Guid> Members { get; }

    }

}

namespace Hackathon.Feature.Teams.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct HasMembers
    {
        public const string TemplateIdString = "1b7e5c2f-5240-4ac4-aaff-c6ef5d29623f";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID Members = new ID("fd1b8fc6-ce8f-4742-8973-50d07e582942");
        public const string Members_FieldName = "Members";

        }
    }
}

namespace Hackathon.Feature.Teams
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Hackathon.Foundation.DataAccess.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{79a5c5aa-92f3-4ae4-b9a6-d93954d87a50}", "", "Feature.Teams")]
    [SitecoreType(TemplateId = Hackathon.Feature.Teams.Constants.HasTeamName.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IHasTeamName : IGlassBase
    {
        
        /// <summary>Represents the Name field (97cb116c-1aea-4d36-be95-b42205d42625).</summary>
        [SitecoreField(FieldName = Hackathon.Feature.Teams.Constants.HasTeamName.Fields.Name_FieldName)]
        string Name { get; }

    }

}

namespace Hackathon.Feature.Teams.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct HasTeamName
    {
        public const string TemplateIdString = "79a5c5aa-92f3-4ae4-b9a6-d93954d87a50";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID Name = new ID("97cb116c-1aea-4d36-be95-b42205d42625");
        public const string Name_FieldName = "Name";

        }
    }
}




namespace Hackathon.Feature.Teams
{
	using global::Sitecore.Data;

	public struct Templates
	{
		
		public struct BasicTeam
		{
            public const string TemplateIdString = "b1b66da1-ec87-4f51-9759-9e4964b2ae0a";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
		}

		public struct HasMembers
		{
            public const string TemplateIdString = "1b7e5c2f-5240-4ac4-aaff-c6ef5d29623f";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID Members = new ID("fd1b8fc6-ce8f-4742-8973-50d07e582942");
				public const string Members_FieldName = "Members";

			}
		}

		public struct HasTeamName
		{
            public const string TemplateIdString = "79a5c5aa-92f3-4ae4-b9a6-d93954d87a50";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID Name = new ID("97cb116c-1aea-4d36-be95-b42205d42625");
				public const string Name_FieldName = "Name";

			}
		}

	}
}

// Hackathon.Feature.Teams.BasicTeam (/sitecore/templates/Feature/Teams/_Basic Team b1b66da1-ec87-4f51-9759-9e4964b2ae0a)

// Hackathon.Feature.Teams.HasMembers (/sitecore/templates/Feature/Teams/_Has Members 1b7e5c2f-5240-4ac4-aaff-c6ef5d29623f)
	// Members (fd1b8fc6-ce8f-4742-8973-50d07e582942)
		// Type: Multilist
		// Section: Data
		// Sort Order: 300
		// Source: /sitecore/content/sitecore-hackathon/Data/Members/Participants

// Hackathon.Feature.Teams.HasTeamName (/sitecore/templates/Feature/Teams/_Has Team Name 79a5c5aa-92f3-4ae4-b9a6-d93954d87a50)
	// Name (97cb116c-1aea-4d36-be95-b42205d42625)
		// Type: Single-Line Text
		// Section: Data
		// Sort Order: 100
		// Source: 

