---
ID: "f84bdf17-d700-42da-ad50-132b4173c6f9"
Parent: "79a5c5aa-92f3-4ae4-b9a6-d93954d87a50"
Template: "79a5c5aa-92f3-4ae4-b9a6-d93954d87a50"
Path: /sitecore/templates/Feature/Teams/_Has Team Name/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T162230Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
