
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All


namespace Hackathon.Feature.SharedComponents.RichText
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Hackathon.Foundation.DataAccess.Models;
    using Glass.Mapper.Sc.Configuration.Attributes;
    using Glass.Mapper.Sc.Fields;
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

    /// <summary>Controls the appearance of the inheriting template in site navigation.</summary>
    ///[RepresentsSitecoreTemplateAttribute("{5bfe17dc-fbe3-4310-83c3-5cf34a93fc85}", "", "Feature.SharedComponents")]
    [SitecoreType(TemplateId = Hackathon.Feature.SharedComponents.RichText.Constants.RichTextSection.TemplateIdString)]
	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public partial interface IRichTextSection : IGlassBase
    {
        
        /// <summary>Represents the Text field (47fa45c7-30c2-42e3-970b-4f8f7cc4b6e0).</summary>
        [SitecoreField(FieldName = Hackathon.Feature.SharedComponents.RichText.Constants.RichTextSection.Fields.Text_FieldName)]
        string Text { get; }

        /// <summary>Represents the Title field (a7e0065b-779b-4ee6-93cf-8a6730753e25).</summary>
        [SitecoreField(FieldName = Hackathon.Feature.SharedComponents.RichText.Constants.RichTextSection.Fields.Title_FieldName)]
        string Title { get; }

    }

}

namespace Hackathon.Feature.SharedComponents.RichText.Constants
{
    using global::Sitecore.Data;
	using System.CodeDom.Compiler;

	[GeneratedCode("Leprechaun", "1.0.0.0")]
    public struct RichTextSection
    {
        public const string TemplateIdString = "5bfe17dc-fbe3-4310-83c3-5cf34a93fc85";
        public static readonly ID TemplateId = new ID(TemplateIdString);

        
        public struct Fields
        {
        public static readonly ID Text = new ID("47fa45c7-30c2-42e3-970b-4f8f7cc4b6e0");
        public const string Text_FieldName = "Text";

        public static readonly ID Title = new ID("a7e0065b-779b-4ee6-93cf-8a6730753e25");
        public const string Title_FieldName = "Title";

        }
    }
}




namespace Hackathon.Feature.SharedComponents
{
	using global::Sitecore.Data;

	public struct Templates
	{
		
		public struct RichTextSection
		{
            public const string TemplateIdString = "5bfe17dc-fbe3-4310-83c3-5cf34a93fc85";
			public static readonly ID TemplateId = new ID(TemplateIdString);

			
			public struct Fields
			{
				public static readonly ID Text = new ID("47fa45c7-30c2-42e3-970b-4f8f7cc4b6e0");
				public const string Text_FieldName = "Text";

				public static readonly ID Title = new ID("a7e0065b-779b-4ee6-93cf-8a6730753e25");
				public const string Title_FieldName = "Title";

			}
		}

	}
}

// Hackathon.Feature.SharedComponents.RichText.RichTextSection (/sitecore/templates/Feature/SharedComponents/Rich Text/Rich Text Section 5bfe17dc-fbe3-4310-83c3-5cf34a93fc85)
	// Text (47fa45c7-30c2-42e3-970b-4f8f7cc4b6e0)
		// Type: Rich Text
		// Section: Data
		// Sort Order: 200
		// Source: 
	// Title (a7e0065b-779b-4ee6-93cf-8a6730753e25)
		// Type: Single-Line Text
		// Section: Data
		// Sort Order: 100
		// Source: 

