---
ID: "9651434c-0a57-4128-978f-2076faec223c"
Parent: "698d10c2-c3d1-4e97-9f1c-11b3b8694ee5"
Template: "698d10c2-c3d1-4e97-9f1c-11b3b8694ee5"
Path: /sitecore/templates/Project/SitecoreHackathon/Content Types/Team/Team/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{04963490-E4FC-4574-B18F-40F6D880E127}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T033942Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "dfc01ac8-1f9c-4fe0-8802-26c7fc09d2c3"
      Hint: Name
      Value: $name
