
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All





namespace Hackathon.Feature.Navigation
{
	using global::Sitecore.Data;

	public struct Templates
	{
		
	}
}

